### ISSUE TITLE
Debug locally

### ISSUE THREAD

**Issue by rsuk** [bharney/JSStarterDocker#49]
This looks like just the kind of fleshed out example I have been looking for, but I'm having trouble getting up and running locally and hoping you might be able to give me a nudge in the right direction.

Did the following according to your instructions:

> npm install webpack webpack-cli -g

.. followed by "dotnet restore" which appeared to work fine.

However, "dotnet build" is returning an error:

EXEC : error : Cannot find module 'D:\ReactStarterPack\StarterPack\node_modules\webpack\bin\webpack.js' [D:\ReactStarterPack\StarterPack\StarterKit.csproj]

I would have though webpack would be resolved by the global install?

**Comment by rsuk** [comment]
Think I have managed to solve it / get around the issue. I first tried setting my NODE_PATH with "setx NODE_PATH %AppData%\npm\node_modules" which didn't appear to help.

Then I came across a post that suggested that I should link the globally installed webpack and webpack-cli - so I did that with:

npm link webpack
npm link webpack-cli

The "dotnet build" then got much further, failing with a missing "node-sass" module. So I ran "node install node-sass --save-dev" and "dotnet build" now completes without error.

Now to see if I can complete the setup and run it locally!

**Comment by rsuk** [comment]
I appear to have hit a problem with the Azure KeyVault when running locally. Could you point in the right direction for what I need to do to run locally re: Azure KeyVault?

**Comment by bharney** [comment]
@rsuk I will certainly need to update the read me with the steps you described. You are correct, unfortunately `webpack`,  `webpack-cli`, and `node-sass` need to be installed globally.

`npm install -g webpack webpack-cli node-sass`

This should get you to the point of getting webpack to build the bundle and chunks and put them into the `ClientApp/dist` (SSR) and `wwwroot/dist` (client) folders. 

Its not actually necessary to setup KeyVault to get the project running locally. So I'll layout the steps for purely local development. And then how to use this projects ARM Template to create the resources in Azure. The following is without docker.

Local Development:
1.) Navigate to `Program.cs`
2.) Comment out the lines for keyVaultConfig Builder
```
               var keyVaultConfigBuilder = new ConfigurationBuilder();
                keyVaultConfigBuilder.AddAzureKeyVault(
                    builtConfig["MSI_ENDPOINT"],
                    builtConfig["MSI_CLIENT"],
                    builtConfig["MSI_SECRET"]);
                var keyVaultConfig = keyVaultConfigBuilder.Build();
                config.AddConfiguration(keyVaultConfig);
```
These lines above use the user secrets manager in Visual Studio 2017 to get the keys to access KeyVault. So for now we do not need them. 
3.) Add the config values that we being retrieved from KeyVault to the `appsettings.json`.
The `appsettings.json` will look like this:
```
{
  "Logging": {
    "IncludeScopes": false,
    "Debug": {
      "LogLevel": {
        "Default": "Warning"
      }
    },
    "Console": {
      "LogLevel": {
        "Default": "Warning"
      }
    }
  },
  "ConnectionStrings": {
    "DefaultConnection": "[YOUR_CONNECTION_STRING]"
  },
  "Token": {
    "Key": "[YOUR_JWT_BEARER_KEY]",
    "Issuer": "[YOUR_JWT_ISSUER_URL]"
  },
  "MailServiceKey": "[YOUR_SENDGRID_API_KEY]",
  "MailServiceUser": "[YOUR_SENDGRID_API_USER]",
  "BlobServiceAccount": "[YOUR_BLOB_STORAGE_ACCOUNT]",
  "BlobServiceKey": "[YOUR_BLOB_STORAGE_KEY]",
   "BlobService": {
        "StorageUrl": "[YOUR_BLOB_STORAGE_URL]/"
    },
  "SeedAccount": {
    "UserName": "admin@email.com",
    "Password": "Your_password123!"
  }
}
```
4.) You dont have to set all of these values to get the project to display the homepage. The only ones that are required are the DefaultConnection, and SeedAccount. At this point you should be able to run the project and get the home page to display. The other values are needed for emailing with SendGrid, and BlobStorage.

**Comment by bharney** [comment]
One of the main problems with handling secrets in .NET Core has been working locally vs deploying to production using AzureDevOps. 

I've been handling this by using the user secrets manager built into VS 2017 to work locally. This prevents me from accidentally committing secrets to source control. I store the key vault access keys or connection string secrets in a `secrets.json` outside of source control, and VS2017 handles the file for me. Additional information can be found [here](https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-2.1&tabs=windows): 
1.) Navigate to Solution Explorer
2.) Right click on `StarterKit > Manage User Secrets`
![image](https://user-images.githubusercontent.com/8311928/47606608-7e46f200-d9ca-11e8-967f-e760f80b1171.png)
3.) Update the `secrets.json` to contain the KeyVault access key or connection string.
```
{
  "MSI_SECRET": "[YOUR_MSI_SECRET]",
  "MSI_ENDPOINT": "[YOUR_KEY_VAULT_URL]/",
  "MSI_CLIENT": "[YOUR_AZURE_AD_APP_ID]",
}
```
More information can been found about Managed Service Identity [here](https://azure.microsoft.com/en-us/blog/keep-credentials-out-of-code-introducing-azure-ad-managed-service-identity/)

The ideal scenario is to build an ARM template that can be checked into source control. But the ARM template itself accesses KeyVault secrets. So before you can even run the ARM template you need to have KeyVault setup. What a pain. I hope to resolve this problem in the future.

The future plan is to update the ARM template to create a KeyVault and pull the values from Secret Manager. Id be making a dependency on KeyVault for all of the Azure Resources, and having config for the KeyVault in the ARM template which would pull from User Secrets Manager in VS 2017. But in the mean time you will need to manually setup KeyVault and reference it in the ARM Template.

**Comment by bharney** [comment]
The TLDR; of it all is to setup KeyVault in Azure. You can get started with Azure KeyVault [here](https://docs.microsoft.com/en-us/azure/key-vault/key-vault-get-started). I recommend using the Azure CLI or PowerShell as it will help you understand the ARM templates. Additional information about getting KeyVault values using `Program.cs` can be found [here](https://docs.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?view=aspnetcore-2.1)

**Comment by bharney** [comment]
Issue with KeyVault will hopefully be resolved soon. Working to fix the ARM Template to create KeyVault as dependency for other Azure Resources. Please see #52 Once the ARM template is updated, you should be able to run and deploy the AzureResourceGroup project. This will allow users to get up and running without all of the pre-requisite knowledge of how to setup KeyVault. However, the down side is it will require an Azure Subscription and cost money to create the resources.

**Comment by bharney** [comment]
Setup scripts and folder structure have been added to the forked repo [JSStarter](https://github.com/bharney/JSStarter). scripts > setup.ps1 should be all that is needed to run the setup. This will spin up the dependencies for the ARM Template and save the secrets to the key vault.
