### ISSUE TITLE
Registration Confirmation Email should not be a protected route and fix typo

### ISSUE THREAD

**Issue by bharney** [bharney/JSStarterDocker#51]
As a new user, when trying to register a new account. After registration, I receive a registration email confirmation to ensure the email is valid. However there are two problems:
- [x] the link for registration has a typo which points to the wrong domain (i.e. sstarter/Account/RegistrationConfirmationEmail... but it should be jsstarter/Account/...)
- [x] When clicking on the confirmation email link, I am directed to the site but then redirected to login page. The alert says I need to login before continuing. However this prevents any users from registering.

**Comment by ghost** [comment]
I see what you mean here. Once I get some free time and get this running locally, I'll take a look at this one as my first pull request. My guess is something with the query string.
